# Header
menu:
    home: /
    dropdown menu:
        google: //google.com/
        yahoo: //yahoo.com/

extmenu:
    github: 
        kywk: //github.com/kywk/
        zodiacg: //github.com/zodiacg/
    hexo: //zespia.tw/hexo/
    theme:
        biture: //github.com/kywk/hexo-theme-biture
        rebiture: //github.com/zodiacg/hexo-theme-rebiture
        landscape: //github.com/tommy351/hexo-theme-landscape
        light: //github.com/tommy351/hexo-theme-light

# Content
excerpt_link: Read More

fancybox: true

since: 2008
